name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        run: docker build -t backend ./backend

      - name: Build Frontend Image
        run: docker build -t frontend ./frontend

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (placeholder)
        run: echo "Deploy step here (e.g., SSH to VM and run docker-compose up)"
