name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t hello-world .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Test the app (basic test)
        run: echo "Tests passed!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Remote VM
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd hello-world-deployment
            git pull
            docker-compose down
            docker-compose up -d --build
